function Hphi = heat_semigroup(phi, t, vareps, lambda_x, dx)
% HEAT_SEMIGROUP  Apply the heat semigroup H_t to a spatial field phi.
%
%   Hphi = heat_semigroup(phi, t, vareps, lambda_x, dx)
%
%   Solves  u(t) = H_t[phi]  where H_t is generated by  eps * d_xx,
%   i.e. H_t[phi] = solution at time t of:
%
%       du/ds = vareps * d_xx u,   s in [0, t]
%       u(0)  = phi
%       du/dx = 0 at x=0, x=1   (Neumann / zero-flux BCs)
%
%   Implementation via DCT-II (Neumann BCs diagonalise under DCT):
%
%       H_t[phi]_hat(k) = exp(-vareps * lambda_x(k) * t) * phi_hat(k)
%
%   where lambda_x(k) are the DCT-II eigenvalues of -d_xx with Neumann BCs.
%
%   Inputs:
%     phi       (nx x 1)  spatial field to propagate
%     t         scalar    propagation time (>= 0)
%     vareps    scalar    diffusion coefficient (same eps as FP constraint)
%     lambda_x  (nx x 1)  DCT-II eigenvalues of -d_xx (precomputed)
%     dx        scalar    grid spacing (for normalisation)
%
%   Output:
%     Hphi      (nx x 1)  phi propagated forward by time t

    if t == 0
        Hphi = phi;
        return;
    end

    decay  = exp(-vareps * lambda_x * t);   % (nx x 1) decay factors
    phi_hat = dct(phi);                      % DCT-II coefficients
    Hphi    = idct(decay .* phi_hat);        % apply decay, back to physical space
    Hphi    = max(Hphi, 0);                  % enforce positivity (rounding errors)
end
